### ISSUE TITLE
Persona Skin does Work, but not right with hairs yet

### ISSUE THREAD

**Issue by suerion** [PresentKim/PersonaSkin#2]
i had added this Plugin 1.0.0 on my debug server and changed the Skin so worse.

it worked on my debug Server, but the hairs are not right yet. ;)
![grafik](https://user-images.githubusercontent.com/55131959/89665926-be464300-d8d9-11ea-9213-c0efe1e0de75.png)

![grafik](https://user-images.githubusercontent.com/55131959/89665903-b2f31780-d8d9-11ea-81ec-4b1d2f5f6e9e.png)

Pocketmine is an barber xD

**Comment by suerion** [comment]
in the visual view it does work normal, but the char has no hairs
![grafik](https://user-images.githubusercontent.com/55131959/89678806-20aa3e00-d8f0-11ea-956f-8644678b13bd.png)


on bending down, you could see the hairs
![grafik](https://user-images.githubusercontent.com/55131959/89678861-36b7fe80-d8f0-11ea-8e34-4e3591df4f43.png)

**Comment by PresentKim** [comment]
# Information
This is not a problem with PMMP or this plugin.
Minecraft TPS view is fixed relative to the head.
Therefore, the thin vertical hair is not visible.
  
# Test in vanila
Vanilla also suffers from this problem.
![_](https://i.ibb.co/89rrRCN/image.png)
![_](https://i.ibb.co/jVp7jwF/image.png)
However, when viewed by third parties, this problem is alleviated.
  
# Test in PMMP
It's simply a matter of can't looking at the thin side, so it looks right if look at it from a slightly distorted angle.
![_](https://i.ibb.co/YWBwGSs/image.png)
